export { WelcomeScreen } from './WelcomeScreen'
export { FileDropOverlay } from './FileDropOverlay'
export { collectFiles } from './dropFiles'
export { SaveStatus } from './SaveStatus'

// Building blocks of the start pages (home, customize), shared so they look and behave the same.
export { RecentList } from './RecentList'
export { RecentSection } from './RecentSection'
export { SampleGrid } from './SampleGrid'
export { SamplesSection, SAMPLES_SECTION_ID } from './SamplesSection'
export { StartPage } from './StartPage'
export { LottiePreview } from './LottiePreview'
export { TruncatedText } from './TruncatedText'
export { useFreshRecents, useStartupSettled } from './hooks'
export { refreshOpenThumbnail } from './autosave'
export { useIo, type DropKind } from './store'
export type { DocumentRoute } from './dialog-ids'
export type { RecentEntry } from './storage'

// Opening files: every path shows the document on the right page (see reveal.ts).
export { explainUnhandledFiles, openFiles, openSample, pickFiles } from './open'
export { openRecent } from './session'
export { revealDocument } from './reveal'
export { buildDownload } from './download'
export { readDocument } from './storage'
export { showOpenUrl } from './urlDownload'
export { DIALOG as IO_DIALOG } from './dialog-ids'
export { describeOpenError } from './messages'
export { notifyError } from './notify'
export { formatDuration, formatFileSize, formatRelativeTime } from './format'
