/**
 * Application menu structure. Entries reference command ids; commands that are not
 * registered are hidden, so menus only show what is actually available.
 */
import type { Dict } from '@/i18n'
import { EASING_PRESETS } from '@/lottie/easing'
import { SPEEDS } from '@/store/playback'

export type MenuEntry = string | '-' | { label: (t: Dict) => string; items: MenuEntry[] }

export interface MenuDef {
  id: string
  label: (t: Dict) => string
  items: MenuEntry[]
}

export const MENUS: MenuDef[] = [
  {
    id: 'file',
    label: (t) => t.app.menu.file,
    items: [
      'file.new',
      'file.open',
      'file.openUrl',
      'file.samples',
      '-',
      'file.importAsLayer',
      'file.switchAnimation',
      '-',
      'file.download',
      'file.export',
      'export.frameLottie',
      'themes.export',
      '-',
      'file.revert',
      'file.close',
      '-',
      'file.toggleAutosave',
      'file.clearRecents',
    ],
  },
  {
    id: 'edit',
    label: (t) => t.app.menu.edit,
    items: [
      'edit.undo',
      'edit.redo',
      'edit.history',
      '-',
      'edit.cut',
      'edit.copy',
      'edit.paste',
      'edit.duplicate',
      'edit.delete',
      '-',
      'edit.selectAll',
      'edit.deselect',
      '-',
      'edit.revealInCode',
    ],
  },
  {
    id: 'view',
    label: (t) => t.app.menu.view,
    items: [
      'view.zoomIn',
      'view.zoomOut',
      'view.zoomFit',
      'view.zoom100',
      'view.zoomSelection',
      '-',
      'view.toggleBounds',
      'view.compare',
      {
        label: (t) => t.app.menu.background,
        items: [
          'view.bg.checker',
          'view.bg.dark',
          'view.bg.light',
          'view.bg.custom',
          '-',
          'view.bg.cycle',
        ],
      },
      { label: (t) => t.app.menu.renderer, items: ['view.renderer.svg', 'view.renderer.canvas'] },
      'view.runExpressions',
      '-',
      'view.canvas',
      'view.code',
      'view.split',
      '-',
      'view.toggleUi',
      'view.toggleLeft',
      'view.toggleRight',
      'view.toggleTimeline',
      '-',
      {
        label: (t) => t.app.menu.theme,
        items: ['view.theme.dark', 'view.theme.light', 'view.theme.system'],
      },
      { label: (t) => t.app.menu.language, items: ['view.language.en', 'view.language.ru'] },
    ],
  },
  {
    id: 'animation',
    label: (t) => t.app.menu.animation,
    items: [
      'anim.settings',
      'anim.timing',
      'anim.trim',
      'anim.resize',
      'anim.fitToContent',
      '-',
      'anim.speedUp',
      'anim.slowDown',
      'anim.reverse',
      'anim.pingPong',
      'anim.addPause',
      '-',
      'anim.colors',
      {
        label: (t) => t.app.menu.colors,
        items: [
          'colors.adjust',
          'colors.invert',
          'colors.grayscale',
          '-',
          'colors.copyPalette',
          'colors.resetAll',
        ],
      },
      'themes.show',
      'themes.newTheme',
      'themes.stopPreview',
      '-',
      'anim.optimize',
      'anim.issues',
      '-',
      'anim.addMarker',
    ],
  },
  {
    id: 'layer',
    label: (t) => t.app.menu.layer,
    items: [
      {
        label: (t) => t.app.menu.newLayer,
        items: [
          'layer.new.rect',
          'layer.new.ellipse',
          'layer.new.star',
          'layer.new.polygon',
          'layer.new.text',
          'layer.new.solid',
          'layer.new.null',
          'layer.new.image',
          '-',
          'layer.new.svg',
        ],
      },
      '-',
      'layer.rename',
      'layer.toggleVisibility',
      'layer.toggleLock',
      'layer.toggleSolo',
      '-',
      'layer.group',
      'layer.ungroup',
      'layer.precompose',
      'layer.unprecompose',
      '-',
      {
        label: (t) => t.inspector.sections.effects,
        items: [
          'effect.add.fill',
          'effect.add.tint',
          'effect.add.tritone',
          '-',
          'effect.add.dropShadow',
          'effect.add.gaussianBlur',
          '-',
          'effect.add.stroke',
          'effect.add.transform',
          '-',
          'effect.removeAll',
        ],
      },
      '-',
      {
        label: (t) => t.app.menu.arrange,
        items: [
          'layer.bringToFront',
          'layer.bringForward',
          'layer.sendBackward',
          'layer.sendToBack',
        ],
      },
      '-',
      'layer.selectParent',
      'layer.selectChildren',
      '-',
      'layer.replaceContent',
      'layer.revealKeyframes',
      'layers.collapseAll',
    ],
  },
  {
    id: 'keyframes',
    label: (t) => t.app.menu.keyframes,
    items: [
      {
        label: (t) => t.app.menu.easing,
        items: EASING_PRESETS.map((p) => `keyframes.easing.${p.id}`),
      },
      'keyframes.easyEase',
      'keyframes.easeIn',
      'keyframes.easeOut',
      'keyframes.toggleHold',
      '-',
      'keyframes.copy',
      'keyframes.cut',
      'keyframes.paste',
      'keyframes.delete',
      'keyframes.selectAll',
      '-',
      'keyframes.reverse',
      'keyframes.distribute',
      '-',
      'keyframes.nudgeLeft',
      'keyframes.nudgeRight',
      'keyframes.nudgeLeft10',
      'keyframes.nudgeRight10',
    ],
  },
  {
    id: 'playback',
    label: (t) => t.app.menu.playback,
    items: [
      'playback.toggle',
      '-',
      'playback.start',
      'playback.end',
      'playback.prevFrame',
      'playback.nextFrame',
      'playback.back10',
      'playback.forward10',
      '-',
      'playback.prevKeyframe',
      'playback.nextKeyframe',
      'playback.prevMarker',
      'playback.nextMarker',
      '-',
      {
        label: (t) => t.app.menu.playMode,
        items: ['playback.mode.loop', 'playback.mode.once', 'playback.mode.bounce'],
      },
      { label: (t) => t.app.menu.speed, items: SPEEDS.map((s) => `playback.speed.${s}`) },
      '-',
      'playback.workStart',
      'playback.workEnd',
      'playback.setWorkStart',
      'playback.setWorkEnd',
      'playback.clearWorkArea',
      '-',
      {
        label: (t) => t.app.menu.timeline,
        items: [
          'timeline.zoomIn',
          'timeline.zoomOut',
          'timeline.zoomFit',
          '-',
          'timeline.toggleGraph',
          'timeline.graphValue',
          'timeline.graphSpeed',
          'timeline.graphNormalize',
          'timeline.graphFit',
          '-',
          'timeline.toggleSnapping',
          'timeline.toggleUnits',
          '-',
          'timeline.moveInPoint',
          'timeline.moveOutPoint',
          'timeline.trimInPoint',
          'timeline.trimOutPoint',
        ],
      },
    ],
  },
  {
    id: 'help',
    label: (t) => t.app.menu.help,
    items: [
      'help.commandPalette',
      'help.shortcuts',
      '-',
      'help.settings',
      'app.install',
      'help.about',
    ],
  },
]
