/**
 * Built-in sample animations (original works made for this project).
 * Loaded lazily so they don't weigh on the initial bundle. All but `bounce` are generated by
 * `scripts/samples/generate.mjs`; the metadata below lets the welcome screen lay out the cards
 * before any sample is loaded (the generator prints the values).
 */
import type { Animation } from '@/lottie/types'

export interface SampleInfo {
  id: string
  /** English display name; the io feature translates it by id. */
  name: string
  load: () => Promise<Animation>
  width: number
  height: number
  fps: number
  /** Duration in frames (op − ip). */
  frames: number
  /** Where the still preview is taken, as a fraction of the duration (an attractive frame). */
  poster: number
}

const json = (m: { default: unknown }) => m.default as Animation

export const SAMPLES: SampleInfo[] = [
  {
    id: 'bounce',
    name: 'Bouncing ball',
    load: () => import('./bounce.json').then(json),
    width: 512,
    height: 512,
    fps: 30,
    frames: 60,
    poster: 0.3,
  },
  {
    id: 'loader',
    name: 'Loader',
    load: () => import('./loader.json').then(json),
    width: 256,
    height: 256,
    fps: 60,
    frames: 90,
    poster: 0.3,
  },
  {
    id: 'success',
    name: 'Success',
    load: () => import('./success.json').then(json),
    width: 256,
    height: 256,
    fps: 60,
    frames: 120,
    poster: 0.6,
  },
  {
    id: 'like',
    name: 'Like',
    load: () => import('./like.json').then(json),
    width: 256,
    height: 256,
    fps: 60,
    frames: 90,
    poster: 0.16,
  },
  {
    id: 'gradient-blob',
    name: 'Gradient blob',
    load: () => import('./gradient-blob.json').then(json),
    width: 512,
    height: 512,
    fps: 30,
    frames: 180,
    poster: 0.15,
  },
  {
    id: 'typing',
    name: 'Typing',
    load: () => import('./typing.json').then(json),
    width: 480,
    height: 270,
    fps: 30,
    frames: 120,
    poster: 0.65,
  },
  {
    id: 'toggle',
    name: 'Toggle',
    load: () => import('./toggle.json').then(json),
    width: 256,
    height: 256,
    fps: 30,
    frames: 90,
    poster: 0.45,
  },
  {
    id: 'orbit',
    name: 'Orbit',
    load: () => import('./orbit.json').then(json),
    width: 512,
    height: 512,
    fps: 30,
    frames: 180,
    poster: 0.1,
  },
]

export function findSample(id: string): SampleInfo | undefined {
  return SAMPLES.find((s) => s.id === id)
}
